### PR TITLE
support onPress

### PR DESCRIPTION
**Pull request by rikur**
mostly based on fork from @mayurkothule with some cleanup.

### CODE REVIEW

**Comment by rikur** [comment]
Ah, the if condition for never gets triggered.. I'll add the default gesture to be onPress again.

**Comment by chawax** [comment]
Exactly what I need. It would be nice to merge this !

**Comment by JeffGuKang** [comment]
@rikur Thanks to PR. Could you resolve the conflict?

**Review by JeffGuKang — CHANGES_REQUESTED** [review]
Resolve conflicts :)

**Comment by rikur** [comment]
FYI, I edited it with the Github conflict editor and didn't test the code right away.

**Pull request closed without merging**
